server:
  port: 8088
  tomcat:
    max-swallow-size: 10MB

# 配置mybatis-plus日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

execute: oracle

spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/springboot?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: root
#      password: smchen123
      driverClassName: oracle.jdbc.driver.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521/helowin
#      username: smc
#      password: smc
      url: jdbc:oracle:thin:@172.23.10.153:1521/hzdb
      username: finance
      password: 5eufZC38gsxbYOVj
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 30
      max-wait: 60000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20
crawlerUrl:
  usd-rmb: https://www.usd-cny.com/usd-rmb.htm
  usd-inr: https://www.usd-cny.com/usdx/inr/
