spring:
  data:
    redis:
      host: 192.168.17.140   # Redis ?????
      port: 6379         # Redis ???
      password: smc123  # Redis ?????????????????
      database: 0        # ?? Redis ??????? 0??? 0-15?
      timeout: 3000ms    # ????????? 3 ??

      lettuce:  # ?? Lettuce ?? Redis ????Spring Boot ?????
        pool:
          max-active: 10  # ?????????????????
          max-idle: 8     # ????????????
          min-idle: 2     # ????????????
          max-wait: 5000ms # ?????????????????
